# Generated by Django 4.2.11 on 2024-04-11 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0009_remove_service_description_remove_service_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=90, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookservice',
            name='user',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
