# Generated by Django 4.2.11 on 2024-04-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category_remove_product_sub_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AddField(
            model_name='product',
            name='is_new_items',
            field=models.BooleanField(default=False),
        ),
    ]
