# Generated by Django 4.2.11 on 2024-04-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_news_product_is_new_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_last_chance',
            field=models.BooleanField(default=False),
        ),
    ]
