# Generated by Django 4.2.11 on 2024-04-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_admin_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='admin_category',
        ),
    ]
