# Generated by Django 4.2.11 on 2024-04-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_large_price_product_medium_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='large_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='medium_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='small_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='xlarge_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
