# Generated by Django 4.2.11 on 2024-04-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_large_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='large_price',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='medium_price',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='small_price',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='xlarge_price',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=10),
            preserve_default=False,
        ),
    ]
