# Generated by Django 4.2.11 on 2024-04-15 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_wishlist_products_remove_wishlist_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='wished_product',
        ),
    ]
