# Generated by Django 4.2.11 on 2024-04-15 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_wishlist_wished_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='products',
            new_name='product',
        ),
    ]
