# Generated by Django 4.2.11 on 2024-04-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_filterable',
            field=models.BooleanField(default=False),
        ),
    ]
